#!/usr/bin/env bash

# Получаем список изменённых файлов в текущем коммите
FILES=$(git diff --cached --name-only --diff-filter=ACM --relative)

# Проверяем, есть ли изменённые файлы
if [ -z "$FILES" ]; then
  echo "🟢 Нет изменённых файлов."
  exit 0
fi

# Исправление стиля с помощью Mago
echo "🔹 Mago format:"
/usr/bin/php vendor/bin/mago format $FILES
if [ $? -ne 0 ]; then
  echo "🔴 Ошибка при перезаписи format!"
  exit 1
else
  MODIFIED_FILES=$(git diff --name-only --diff-filter=M)

  if [[ ! -z "${MODIFIED_FILES}" ]]; then
      git add ${MODIFIED_FILES}
  fi

  echo "🟢 Mago format OK"
fi

# Проверка стиля с помощью Mago
echo "🔹 Mago lint:"
/usr/bin/php vendor/bin/mago lint $FILES
if [ $? -ne 0 ]; then
  echo "🔴 Ошибка при проверке lint!"
  exit 1
else
  echo "🟢 Mago lint OK"
fi

# Проверка синтаксиса с помощью Mago
echo "🔸 Mago analyze:"
/usr/bin/php vendor/bin/mago analyze $FILES
if [ $? -ne 0 ]; then
  echo "🔴 Ошибка при проверке analyze!"
  exit 1
else
  echo "🟢 Mago analyze OK"
fi

exit 0
